version: '3.8' # Puedes borrar esta línea si te molesta el 'WARN'

services:

  # Servicio de Búsqueda (El que tenías)
  elasticsearch-dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  # ¡¡ESTA ES LA PARTE QUE FALTABA!!
  # Servicio de Base de Datos (Tus usuarios T6)
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=sophia
      - POSTGRES_PASSWORD=sophia_password
      - POSTGRES_DB=sophia_db
    ports:
      - "5432:5432" # Expone el puerto 5432 a tu localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  elastic_data:
  postgres_data: